# run docker compose
- name: Run Docker Compose build
  community.docker.docker_compose:
    project_src: "{{ app_path }}"
    build: yes

- name: Run Docker Compose
  community.docker.docker_compose:
    project_src: "{{ app_path }}"
    state: present
    
