# pip install requests google-auth
# ansible-playbook 1-vpc.yaml
---
- name: Manage VPC
  hosts: localhost
  gather_facts: no
  tasks:
    # https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_compute_network_module.html
    - name: Create Network
      google.cloud.gcp_compute_network:
        name: "{{ network_name }}"
        auto_create_subnetworks: false
        project: "{{ project }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ service_account_file }}"
        routing_config:
          routing_mode: "REGIONAL"
        mtu: 1460
        state: "{{ 'absent' if delete else 'present' }}"
      tags: 
        - vpc
      register: network
      
    # https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_compute_global_address_module.html
    - name: Create Global IP address
      google.cloud.gcp_compute_global_address:
        name: "{{ address_name }}"
        project: "{{ project }}"
        address_type: "INTERNAL"
        network:
          selfLink: https://www.googleapis.com/compute/v1/projects/{{ project }}/global/networks/{{ network_name }}
        prefix_length: 16
        purpose: "VPC_PEERING"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ service_account_file }}"
        state: "{{ 'absent' if delete else 'present' }}"
      tags:
        - vpc-address
      register: address