# https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_compute_subnetwork_module.html
# ansible-playbook 3-subnetwork.yaml
---
- name: Create Subnetwork
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create a subnetwork
      google.cloud.gcp_compute_subnetwork:
        name: "{{ subnetwork_name }}"
        region: "{{ region }}"
        network: 
          selfLink: https://www.googleapis.com/compute/v1/projects/{{ project }}/global/networks/{{ network_name }}
        ip_cidr_range: "10.0.0.0/16"
        secondary_ip_ranges:
          - range_name: "k8s-pods-ip-range"
            ip_cidr_range: "10.48.0.0/14"
          - range_name: "k8s-services-ip-range"
            ip_cidr_range: "10.52.0.0/20"
        project: "{{ project }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ service_account_file }}"
        private_ip_google_access: true
        state: "{{ 'absent' if delete else 'present' }}"
      register: subnetwork