# https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_compute_firewall_module.html
# ansible-playbook 5-firewall.yaml
---
- name: Create Firewall Rule
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create a firewall rule
      google.cloud.gcp_compute_firewall:
        name: "allow-ssh"
        network: 
          selfLink: https://www.googleapis.com/compute/v1/projects/{{ project }}/global/networks/{{ network_name }}
        allowed:
          - IPProtocol: tcp
            ports: ['22']
        source_ranges: ["0.0.0.0/0"]
        project: "{{ project }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ service_account_file }}"
        state: present
      register: firewall
      tags:
        - firewall
    - name: Delete Firewall Rule
      google.cloud.gcp_compute_firewall:
        name: "allow-ssh"
        network: 
          selfLink: https://www.googleapis.com/compute/v1/projects/{{ project }}/global/networks/{{ network_name }}
        project: "{{ project }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ service_account_file }}"
        state: absent
      tags:
        - never
        - delete