# https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_compute_firewall_module.html
# ansible-playbook 5-firewall.yaml
---
- name: Create Firewall Rule
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create a firewall rule
      google.cloud.gcp_compute_firewall:
        name: "allow-ssh"
        network: "{{ network_name }}"
        allowed:
          - IPProtocol: tcp
            ports: ['22']
        source_ranges: ["0.0.0.0/0"]
        project: "{{ project }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ service_account_file }}"
        state: present
      register: firewall