# https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_compute_firewall_module.html
# ansible-playbook 6-firewall.yaml
---
- name: Create Firewall Rule
  hosts: localhost
  gather_facts: no
  tasks:
    # https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_compute_firewall_module.html
    - name: Create a firewall rule
      google.cloud.gcp_compute_firewall:
        name: "allow-ssh"
        network: 
          selfLink: https://www.googleapis.com/compute/v1/projects/{{ project }}/global/networks/{{ network_name }}
        allowed:
          - ip_protocol: tcp
            ports: ['22']
        source_ranges: ["0.0.0.0/0"]
        project: "{{ project }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ service_account_file }}"
        state: "{{ 'absent' if delete else 'present' }}"
      register: firewall
      tags:
        - firewall