---
# defaults file for consul
consul_version: "1.18.1"

# start consul by default
consul_start: true

# should be vault-ed
# generate with `consul keygen`
consul_encryptkey: "JWl3tmFfcLK5G1e5QH5Ggn4CYum4wnox8YDjR9SaE7o="

consul_servers: ["192.168.1.1"]
