- name: Install RKE2 for Master
  ansible.builtin.shell: curl -sfL https://get.rke2.io | sh -

- name: Enable RKE2 server service
  ansible.builtin.systemd:
    name: rke2-server.service
    enabled: yes

- name: Start RKE2 server service
  ansible.builtin.systemd:
    name: rke2-server.service
    state: started

- name: Get RKE2 token
  command: cat /var/lib/rancher/rke2/server/node-token
  register: rke_token
  changed_when: false
  run_once: true

- name: Save rke2 token
  set_fact:
    rke_token: "{{ rke_token.stdout }}"
  run_once: true

- name: Save manamasterger IP
  set_fact:
    rke_master_ip: "{{ ansible_host }}"
  run_once: true