# Generate ssl

# Generate a self-signed certificate (ca.cert) and a private key (consul.key):
# openssl req -x509 -newkey rsa:4096 -keyout consul.key -out ca.cert -days 365 -nodes -subj "/CN=example.com"

# Generate a Certificate Signing Request (CSR) using the private key:
# openssl req -new -key consul.key -out consul.csr -subj "/CN=example.com"

# Sign the CSR with the self-signed certificate to create a new certificate (consul.cert):
# openssl x509 -req -in consul.csr -CA ca.cert -CAkey consul.key -CAcreateserial -out consul.cert -days 365

# get ca.cert, consul.cert, and consul.key
# ansible-playbook consul.yaml
- name: Privision Consul Cluster
  become: yes
  hosts: consul
  roles:
    - consul