- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Start nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Override proxy conf
  copy:
    src: ./../files/nginx/includes/proxy.conf
    dest: "{{ nginx_conf_path }}/proxy.conf"

- name: Override nginx conf
  template:
    src: ./../files/nginx/default.conf.j2
    dest: /etc/nginx/conf.d/default.conf

- name: restart nginx service
  service: name=nginx state=restarted