---

- name: Add Boundary Env
  template:
    src: boundary.env.j2
    dest: /etc/boundary.d/boundary.env

- name: Add Controller Config
  template:
    src: controller.hcl.j2
    dest: /etc/boundary.d/controller.hcl

- name: Initialize Database
  ansible.builtin.shell:
    cmd: "boundary database init -config /etc/boundary.d/controller.hcl"