---
- name: Download and overwrite HashiCorp GPG key
  ansible.builtin.shell: |
    wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor --yes -o /usr/share/keyrings/hashicorp-archive-keyring.gpg

- name: Add HashiCorp repository
  ansible.builtin.shell:
    cmd: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

- name: Update all installed packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes

- name: Install boundary and certbot
  ansible.builtin.apt:
    name:
      - boundary
      - certbot
      - lsof
    state: present

- name: Check if port 80 is in use
  ansible.builtin.shell: |
    lsof -i :80 -t || true
  register: port_80_pid

- name: Stop process using port 80 if it exists
  ansible.builtin.shell: |
    kill -9 {{ item }} || true
  loop: "{{ port_80_pid.stdout_lines }}"
  when: port_80_pid.stdout != ''
  ignore_errors: yes

- name: Verify Boundary installation
  ansible.builtin.command:
    cmd: "boundary -version"
  register: boundary_version_output

- name: Show Boundary version
  ansible.builtin.debug:
    msg: "{{ boundary_version_output.stdout }}"

- name: Create Boundary KMS Directory
  ansible.builtin.file:
    path: /usr/boundary/
    mode: 0755
    state: directory

# can be inserted when provision the VMs
# - name: Add KMS Service Account
#   copy:
#     src: ./../files/kms-sa.json
#     dest: /usr/boundary/kms-sa.json
- name: Add KMS Service Account
  ansible.builtin.copy:
    src: /home/boundary/kms-sa.json
    dest: /usr/boundary/kms-sa.json
    remote_src: yes