---
# tasks file for boundary

- include_tasks: deps.yaml

- include_tasks: directory.yaml

- include_tasks: certbot.yaml
  when:
  - "'boundary_controller' in group_names"

- include_tasks: postgres.yaml
  when:
  - "'boundary_db' in group_names"

- include_tasks: configuration.yaml
  when:
  - "'boundary_controller' in group_names"

- include_tasks: service.yaml