---

- name: Install PostgreSQL server
  ansible.builtin.apt:
    name: postgresql
    state: present

- name: Ensure PostgreSQL service is enabled and running
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: yes

- name: Check if PostgreSQL user exists
  ansible.builtin.shell: |
    sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='{{ pg_username }}';"
  register: user_exists
  changed_when: false

- name: Create PostgreSQL user if it does not exist
  ansible.builtin.shell: |
    sudo -u postgres psql -c "CREATE USER {{ pg_username }} WITH PASSWORD '{{ pg_password }}';"
  when: user_exists.stdout != "1"

- name: Check if PostgreSQL database exists
  ansible.builtin.shell: |
    sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='{{ pg_dbname }}';"
  register: db_exists
  changed_when: false

- name: Create PostgreSQL database if it does not exist
  ansible.builtin.shell: |
    sudo -u postgres psql -c "CREATE DATABASE {{ pg_dbname }} WITH OWNER {{ pg_username }};"
  when: db_exists.stdout != "1"

- name: Set superuser to the user on the database
  ansible.builtin.shell:
    cmd: >
      sudo -u postgres psql -c "ALTER ROLE {{ pg_username }} WITH SUPERUSER;"

- name: Grant permissions to the user on the database
  ansible.builtin.shell:
    cmd: >
      sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE {{ pg_dbname }} TO {{ pg_username }};"