---
- name: Enable Boundary service
  ansible.builtin.systemd:
    name: boundary
    enabled: yes
    state: started

- name: Set Boundary Log Directory
  ansible.builtin.file:
    path: /var/log/boundary
    mode: 0777
    state: directory
    