---
- name: Check if OpenSSL configuration exists
  stat:
    path: "{{ openssl_cnf_file }}"
  register: openssl_config

- name: Copy OpenSSL configuration
  template:
    src: openssl.cnf.j2
    dest: "{{ openssl_cnf_file }}"
  when: not openssl_config.stat.exists

- name: Check if OpenSSL Cert exists
  stat:
    path: "{{ boundary_cert_pem }}"
  register: boundary_cert_file

- name: Generate private key and certificate
  command:
    cmd: "{{ item }}"
  with_items:
    - openssl genpkey -algorithm RSA -out {{ ca_key_pem }}
    - openssl req -x509 -new -nodes -key {{ ca_key_pem }} -sha256 -days 3650 -out {{ ca_pem }} -subj "/CN={{ public_url }}"
    - openssl genpkey -algorithm RSA -out {{ boundary_key_pem }}
    - openssl req -new -key {{ boundary_key_pem }} -out {{ boundary_csr }} -subj "/CN={{ ansible_default_ipv4.address }}"
    - openssl x509 -req -in {{ boundary_csr }} -CA {{ ca_pem }} -CAkey {{ ca_key_pem }} -CAcreateserial -out {{ boundary_cert_pem }} -days 365 -extensions v3_req -extfile {{ openssl_cnf_file }}
  delegate_to: "{{ groups['boundary_controller'][0] }}"
  run_once: true
  when: not boundary_cert_file.stat.exists

- name: Fetch certificate from the node
  ansible.builtin.fetch:
    src: "{{ boundary_cert_pem }}"
    dest: "./certs/{{ inventory_hostname }}/boundary-cert.pem"
    flat: yes
  delegate_to: "{{ groups['boundary_controller'][0] }}"
  run_once: true

- name: Fetch private key from the node
  ansible.builtin.fetch:
    src: "{{ boundary_key_pem }}"
    dest: "./certs/{{ inventory_hostname }}/boundary-key.pem"
    flat: yes
  delegate_to: "{{ groups['boundary_controller'][0] }}"
  run_once: true

- name: Ensure the destination directory exists on all controller nodes
  ansible.builtin.file:
    path: /etc/boundary.d/tls
    state: directory
    mode: '0755'
  loop: "{{ groups['boundary_controller'] }}"

- name: Distribute certificate to all controller nodes
  ansible.builtin.copy:
    src: "./certs/{{ inventory_hostname }}/boundary-cert.pem"
    dest: "{{ tls_dir }}/boundary-cert.pem"
    mode: '0644'
  loop: "{{ groups['boundary_controller'] }}"

- name: Distribute private key to all controller nodes
  ansible.builtin.copy:
    src: "./certs/{{ inventory_hostname }}/boundary-key.pem"
    dest: "{{ tls_dir }}/boundary-key.pem"
    mode: '0644'
  loop: "{{ groups['boundary_controller'] }}"