---
- name: Copy Common Config
  ansible.builtin.template:
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0640
    backup: yes

- name: Copy Server Config
  ansible.builtin.template:
    src: server.hcl.j2
    dest: /etc/consul.d/server.hcl
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0640
    backup: yes
  when: "'consul_server' in group_names"
  
- name: Copy client Config
  ansible.builtin.template:
    src: client.hcl.j2
    dest: /etc/consul.d/client.hcl
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0640
    backup: yes
  when: "'consul_client' in group_names"