---
- name: Create Consul Data Directory
  ansible.builtin.file:
    path: /var/consul
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0750
    state: directory

- name: Create Consul Directory
  ansible.builtin.file:
    path: /opt/consul/bin
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0750
    state: directory

- name: Create Consul Log Directory
  ansible.builtin.file:
    path: /var/log/consul
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0750
    state: directory