---
- name: Check Version Installed
  ansible.builtin.shell: |
         set -o pipefail
         if [ -f /opt/consul/bin/consul ]; then
             /opt/consul/bin/consul --version|awk 'NR==1{print $2}' |cut -dv -f2
         fi
  args:
    executable: /bin/bash
  register: consul_version_check
  changed_when: consul_version_check.stdout != consul_version

- name: Download Consul Software
  ansible.builtin.unarchive:
    src: "{{ consul_zip_url }}"
    dest: /opt/consul/bin
    remote_src: yes
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0750
  when: consul_version_check.stdout != consul_version

- name: Copy Startup Script (systemd)
  ansible.builtin.template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
    owner: "root"
    group: "root"
    mode: 0750
    backup: no
  notify:
    - Enable consul
    - Start consul
  when: ansible_service_mgr == 'systemd'

- name: Copy Startup Script (sysvinit)
  ansible.builtin.template:
    src: consul_sysvinit.j2
    dest: /etc/init.d/consul
    owner: "root"
    group: "root"
    mode: 0750
    backup: no
  notify:
    - Enable consul
    - Start consul
  when: ansible_service_mgr == 'upstart'
