# install dependencies

---
- name: Update apt and install necessary packages
  apt:
    update_cache: yes
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common', 'wget', 'zip']
    state: present