---
- name: Override nginx conf
  template:
    src: ./../templates/nginx.conf.j2
    dest: /etc/nginx/conf.d/default.conf

- name: Start nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
    
- name: restart nginx service
  service: name=nginx state=restarted