---

- name: Add essyncer and elasticsearch objects to configs.yaml
  ansible.builtin.shell:
    cmd: >
      jq '.essyncer = {} | .elasticsearch = {}' {{ app_dir }}/configs.json >
      {{ app_dir }}/configs.json.tmp && mv {{ app_dir }}/configs.json.tmp {{ app_dir }}/configs.json

- name: Run npm command to deploy databases for erxes
  ansible.builtin.shell:
    cmd: npm run erxes deploy-dbs
    chdir: "{{ app_dir }}"

- name: Read MongoDB password from configs.json
  ansible.builtin.slurp:
    src: "{{ app_dir }}/configs.json"
  register: configs_content

- name: Set MongoDB password as a fact
  ansible.builtin.set_fact:
    mongodb_password: "{{ (configs_content['content'] | b64decode | from_json)['mongo']['password'] }}"

- name: Execute MongoDB command inside the Docker container
  community.docker.docker_container_exec:
    container: "mongo-0"  # Replace with your MongoDB container name
    command: >
      bash -c "echo 'rs.initiate();' | mongo -u erxes -p {{ mongodb_password }}"  

- name: Run erxes up with --uis option
  ansible.builtin.shell:
    cmd: npm run erxes up -- --uis
    chdir: "{{ app_dir }}" 