---
- name: Generate a base64-encoded key for MongoDB
  ansible.builtin.shell:
    cmd: openssl rand -base64 756 > mongo-key
    chdir: "{{ app_dir }}"
  args:
    creates: mongo-key

- name: Set permissions and ownership for mongo-key
  ansible.builtin.file:
    path: "{{ app_dir }}/mongo-key"
    mode: "0400"

- name: Generate a new RSA private key and self-signed certificate
  ansible.builtin.shell:
    cmd: openssl req -newkey rsa:2048 -nodes -keyout key.pem -x509 -days 365 -out certificate.pem -subj "/CN=localhost"
    chdir: "{{ app_dir }}"
  args:
    creates: certificate.pem

- name: Concatenate key.pem and certificate.pem into mongo.pem
  ansible.builtin.shell:
    cmd: cat key.pem certificate.pem > mongo.pem
    chdir: "{{ app_dir }}"
  args:
    creates: mongo.pem
  