---

- name: Initialize Docker Swarm
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ ansible_default_ipv4.address }}"

- name: Create an attachable overlay Docker network
  community.docker.docker_network:
    name: erxes
    driver: overlay
    attachable: yes
    state: present