galaxy_info:
  role_name: swarm
  author: Glend Maatita
  description: Provision Docker Swarm Cluster
  company: OnXP
  license: MIT

  min_ansible_version: "2.1"
  platforms:
  - name: Ubuntu
    versions:
    - jammy

  galaxy_tags: ["docker", "swarm"]

dependencies: []
