# ansible-playbook -v ping.yaml
# More of builtin function: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/index.html
- name: Ping for healthcheck
  hosts: webservers
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: "Pong"