networks:
  exercise_network:
    driver: bridge

services:
  exercise-app:
    image: glendmaatita/exercise-app:v1.0.2
    container_name: "exercise-app"
    ports:
      - "3000:3000"
    networks:
      - exercise_network
