---
- name: Create /opt/nomad directory
  ansible.builtin.file:
    path: /opt/nomad
    state: directory
    mode: '0755'

- name: Create nomad user
  ansible.builtin.user:
    name: nomad
    system: yes
    home: /etc/nomad.d
    shell: /bin/false

- name: Create Nomad config
  copy:
    src: ./files/nomad.service.server
    dest: /etc/systemd/system/nomad.service
  when: "'nomad_server' in group_names"

- name: Create Nomad config
  copy:
    src: ./files/nomad.service.client
    dest: /etc/systemd/system/nomad.service
  when: "'nomad_client' in group_names"

- name: Set common config
  ansible.builtin.file:
    path: /etc/nomad.d/ssl
    state: directory
    mode: '0700'

- name: Set datacenter
  template:
    src: ./files/nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl

- name: Set node as server
  template:
    src: ./files/server.hcl.j2
    dest: /etc/nomad.d/server.hcl
  when: "'nomad_server' in group_names"

- name: Set node as client
  template:
    src: ./files/client.hcl.j2
    dest: /etc/nomad.d/client.hcl
  when: "'nomad_client' in group_names"

# Used by consul as well

- name: Check if OpenSSL configuration exists
  stat:
    path: /etc/nomad.d/ssl/openssl.cnf
  register: openssl_config

- name: Check if OpenSSL Cert exists
  stat:
    path: /etc/nomad.d/ssl/consul_cert_file
  register: consulcertconfig

- name: Copy OpenSSL configuration
  template:
    src: ./files/openssl.cnf.j2
    dest: /etc/nomad.d/ssl/openssl.cnf
  when: not openssl_config.stat.exists

- name: Generate private key and certificate
  vars:
    cert_days: 365
    consul_key_file: /etc/nomad.d/ssl/consul.key
    ca_cert_file: /etc/nomad.d/ssl/ca.cert
    consul_cert_file: /etc/nomad.d/ssl/consul.cert
    csr_file: /etc/nomad.d/ssl/consul.csr
    openssl_cnf_file: /etc/nomad.d/ssl/openssl.cnf
  command:
    cmd: "{{ item }}"
  with_items:
    - openssl req -x509 -nodes -days {{ cert_days }} -newkey rsa:4096 
      -keyout {{ consul_key_file }} -out {{ consul_cert_file }} -config {{ openssl_cnf_file }}
    - openssl req -new -key {{ consul_key_file }} -out {{ csr_file }} -config {{ openssl_cnf_file }}
    - openssl x509 -req -in {{ csr_file }} -CA {{ consul_cert_file }} -CAkey {{ consul_key_file }} -CAcreateserial -out {{ ca_cert_file }} -days {{ cert_days }}
  when: not consulcertconfig.stat.exists