# sudo apt-get update && sudo apt-get install nomad
- name: Install nomad
  apt:
    update_cache: yes
    name: ['nomad']
    state: present

# curl -L -o cni-plugins.tgz "https://github.com/containernetworking/plugins/releases/download/v1.0.0/cni-plugins-linux-$( [ $(uname -m) = aarch64 ] && echo arm64 || echo amd64)"-v1.0.0.tgz && \
- name: Determine architecture
  command: uname -m
  register: system_arch

- name: Set download URL for CNI plugins
  set_fact:
    cni_plugins_url: "https://github.com/containernetworking/plugins/releases/download/v1.0.0/cni-plugins-linux-{{ 'arm64' if system_arch.stdout == 'aarch64' else 'amd64' }}-v1.0.0.tgz"

- name: Download CNI plugins
  get_url:
    url: "{{ cni_plugins_url }}"
    dest: "/tmp/cni-plugins.tgz"

# sudo mkdir -p /opt/cni/bin && \
# sudo tar -C /opt/cni/bin -xzf cni-plugins.tgz
- name: Create directory for CNI plugins
  file:
    path: /opt/cni/bin
    state: directory

- name: Extract CNI plugins
  unarchive:
    src: "/tmp/cni-plugins.tgz"
    dest: "/opt/cni/bin"
    remote_src: yes

# echo 1 | sudo tee /proc/sys/net/bridge/bridge-nf-call-arptables 
# echo 1 | sudo tee /proc/sys/net/bridge/bridge-nf-call-ip6tables 
# echo 1 | sudo tee /proc/sys/net/bridge/bridge-nf-call-iptables

- name: Ensure net.bridge.bridge-nf-call-arptables is set to 1
  sysctl:
    name: net.bridge.bridge-nf-call-arptables
    value: 1
    state: present
    sysctl_set: yes

- name: Ensure net.bridge.bridge-nf-call-ip6tables is set to 1
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: 1
    state: present
    sysctl_set: yes

- name: Ensure net.bridge.bridge-nf-call-iptables is set to 1
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present
    sysctl_set: yes
# net.bridge.bridge-nf-call-arptables = 1
# net.bridge.bridge-nf-call-ip6tables = 1
# net.bridge.bridge-nf-call-iptables = 1

- name: Set net.bridge.bridge-nf-call-arptables to 1
  sysctl:
    name: net.bridge.bridge-nf-call-arptables
    value: '1'
    state: present
    sysctl_set: yes
    reload: yes

- name: Set net.bridge.bridge-nf-call-ip6tables to 1
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    state: present
    sysctl_set: yes
    reload: yes

- name: Set net.bridge.bridge-nf-call-iptables to 1
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present
    sysctl_set: yes
    reload: yes