- name: Install k3s agent
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL={{ channel }} K3S_URL={{ k3s_server_url }} K3S_TOKEN={{ k3s_token }} sh -s -
  args:
    executable: /bin/bash