---
- name: Initialize Swarm
  community.general.docker_swarm:
    state: present
    advertise_addr: "{{ ansible_host }}"
    
- name: Get worker join token
  command: docker swarm join-token worker -q
  register: join_token
  changed_when: false

- name: Save manager IP
  set_fact:
    swarm_manager_ip: "{{ ansible_host }}"
  run_once: true

- name: Get worker join token
  command: docker swarm join-token worker -q
  register: join_token
  changed_when: false
  run_once: true
  
- name: Save join token
  set_fact:
    swarm_manager_join_token: "{{ join_token.stdout }}"
  run_once: true