# define user and group

---
- name: Add docker users to the docker group.
  user:
    name: "{{ item }}"
    groups: "{{ docker_group }}"
    append: true
  with_items: "{{ docker_users }}"
- name: restart docker
  service:
    name: docker
    state: restarted
- name: test docker
  shell: docker run hello-world